name: self_hosted_runner
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Deploy, world!
